name: Continuous Integration
on:
  push:
    branches:
      - master
      - develop

jobs:
  dispatch_newsletter:
    name: Dispatch newsletter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send emails
        uses: ./.github/actions/dispatch-newsletter
        with:
          TOKEN: ${{ secrets.AUTHENTICATION }}
          URL: ${{ secrets.URL_NEWSLETTER }}
