name: Test SDK with PHPUnit
on: [push, pull_request]

jobs:
    build:
        name: Test SDK
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install Composer
              run: |
                wget -qO- composer-setup.php https://getcomposer.org/installer | php -- composer-setup.php
                composer --version

            - name: Install PHPUnit e Dependencies
              run: |
                cd upload/system/library/PagSeguro
                composer install
                composer require phpunit/phpunit

            - name: Run Tests
              run: |
                cd upload/system/library/PagSeguro
                php vendor/bin/phpunit

            - name: PHPCS
              run: |
                cd upload/system/library/PagSeguro
                composer phpcs
